---
title: "Geography 176 A"
author: "[Kiki Takeuchi](https://github.com/ktakeuchi2)"
subtitle: 'Lab 02: COVID-19 Pandemic'
output: 
  html_document:
    theme: journal
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(knitr)
library(readxl)
library(zoo)
library(ggthemes)
```

#### Question 1: COVID Cases in California
COVID Data from [NY Times](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv).

```{r, message=FALSE, warning=FALSE, echo=FALSE}
url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'
covid = read_csv(url)
```
Daily New Cases
```{r, message=FALSE, warning=FALSE, echo=FALSE}
dat = covid %>% 
  filter(state == "California") %>% 
  group_by(county) %>% 
  mutate(newCases = cases - lag(cases)) %>% 
  ungroup() %>% 
  filter(date == max(date)) 
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
most_cases = dat %>%
  group_by(county) %>% 
  summarise(sum_cases = sum(cases)) %>% 
  arrange(-sum_cases) %>% 
  slice_max(sum_cases, n = 5) %>% 
  select(county, sum_cases)

knitr::kable(most_cases,
            caption = "Most Cumulative Cases in California",
            col.names = c("County", "Cases")) %>% 
  kableExtra::kable_styling("striped", full_width = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
most_new_cases = dat %>% 
    slice_max(newCases, n = 5) %>% 
    select(county, newCases)

knitr::kable(most_new_cases, 
             caption = "Most New Cases in California",
             col.names = c("County", "New Cases")) %>% 
  kableExtra::kable_styling("striped", full_width = TRUE)
```


#### Number of Cases in the Last 14 Days Per 100,000 People
```{r, message=FALSE, warning=FALSE, echo=FALSE}
PopulationEstimates <- read_excel("../data/PopulationEstimates.xls", 
    skip = 2) 
pop = PopulationEstimates %>%
  select(fips = "FIPStxt", pop19 = "POP_ESTIMATE_2019", state = "State", county = "Area_Name")
```

Cases Per Capita
```{r, message=FALSE, warning=FALSE, echo=FALSE}
cal <- right_join(pop, dat, by = "fips")
  
cases_pcapita = cal %>% 
  mutate(cases_pcap = (cases/pop19)* 100000) %>% 
  slice_max(cases_pcap, n = 5) %>% 
  select(county.y, cases_pcap)
knitr::kable(cases_pcapita,
             caption = "Most Cumulative Cases Per Capita",
             col.names = c("County", "Cases Per Capita")) %>%
  kableExtra::kable_styling("striped", full_width = TRUE)         
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
newcases_pcapita = cal %>% 
  mutate(newcases_pcap = (newCases/pop19) * 100000) %>% 
  slice_max(newcases_pcap, n = 5) %>% 
  select(county.y, newcases_pcap)
knitr::kable(newcases_pcapita,
             caption = "Most New Cases Per Capita",
             col.names = c("County", "New Cases Per Capita")) %>%
  kableExtra::kable_styling("striped", full_width = TRUE)
```
Cases Per Capita in the Last 14 Days
```{r, message=FALSE, warning=FALSE, echo=FALSE}
last_14 = cal %>%
  filter(date >= max(date)-13) %>%
  select(county.y, newCases, pop19, cases, date) %>% 
  group_by(county.y, pop19) %>%
  summarize(tot_cases = sum(newCases, na.rm = TRUE), tot_cum_cases = sum(cases, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(safe = tot_cases/(pop19/100000)) %>% 
  filter(safe < 100)
```

Total Number of Cases
```{r, message=FALSE, warning=FALSE, echo=FALSE}
sum(cal$cases)
```

Total Number of New Cases
```{r, message=FALSE, warning=FALSE, echo=FALSE}
sum(cal$newCases)
```
Total Number of Safe Counties
```{r, message=FALSE, warning=FALSE, echo=FALSE}
sum(nrow(last_14))
```


#### Question 2: COVID Cases in New York, California, Louisiana, and Florida

```{r, message=FALSE, warning=FALSE, echo=FALSE}
four_states = covid %>%
  filter(state %in% c("New York", "California", "Louisiana", "Florida")) %>%
  group_by(state, date) %>%
  summarize(cases = sum(cases)) %>%
  ungroup() %>% 
  group_by(state) %>% 
  mutate(newCases = cases - lag(cases),
         roll7 = rollmean(newCases, 7, fill = NA, align = "right")) %>%
  ungroup() %>% 
  filter(newCases > 0)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
ggplot(data = four_states, aes(x = date)) +
  geom_col(aes(y = newCases), color = NA, fill = "lightblue3") +
  geom_line(aes(y = roll7, color = "blue", size = 1)) +
  labs(title = "Daily New Cases and 7-Day Rolling Mean",
       x = "Date",
       y = "Cases",
       subtitle = "Data Source: NY Times",
       caption = "Lab 02 Question 02") +
  facet_wrap(~state, scales = "free_y") +
  theme_linedraw() +
  theme(plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(size = 14, face = 'bold')) +
  theme(legend.position = 'none') +
  ggsave(file = "../img/four-states-7-day-rolling-mean.png")
```
##### Impacts of Scale on Data Interpretation

```{r, message=FALSE, warning=FALSE, echo=FALSE}
state_dat = covid %>% 
  filter(state %in% c("New York", "California", "Louisiana", "Florida")) %>% 
    right_join(pop, by = "fips")
```


